
# Load-balancer
lb:
  image: eeacms/haproxy
  ports:
    - "80"
    - "70"
  links:
    - web
    - insertnote
    - deletenote
    - stat
    - notelist
    - getnote

  restart: always

# Infrastructure
mongodb:
   image: tobilg/mongodb-marathon
   ports:
     - "27777:27017"

rabbit:
   image: rabbitmq
   ports:
     - "5672:5672"

consul1:
  image: "progrium/consul:latest"
  ports:
    - "8400:8400"
    - "8500:8500"
  links:
    - web
    - insertnote
    - deletenote
    - stat
    - notelist
    - getnote
  command: "-server -bootstrap -agent"

# Microservices
insertnote:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8081:8080"

notelist:
   build: ./services/notelist
   links:
     - mongodb
     - rabbit
   ports:
     - "8082:8080"

deletenote:
   build: ./services/deletenote
   links:
     - mongodb
     - rabbit
   ports:
     - "8083:8080"

getnote:
   build: ./services/getnote
   links:
    - mongodb
    - rabbit
   ports:
    - "8084:8080"

stat:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8085:8080"

# web
web:
   build: ./notesapp
   environment:
     SERVICE_80_NAME: "notesapp"
     SERVICE_80_TAGS: "web, notesapp"
   ports:
     - "80:3000"
