lb:
   image: nginx
   links:
      - insertnode:insertnode
   ports:
      - "8080:8080"

mongodb:
   image: mongo
   ports:
     - "27017:27017"

rabbit:
   image: rabbitmq
   ports:
     - "5672:5672"

insertnode:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"

notelist:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"