
# Load-balancer
lb:
  image: eeacms/haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web
  restart: always

# Service discovery
consul:
  command: -server -bootstrap -advertise 10.0.2.15
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"


# Infrastructure
mongodb:
   image: mongo
   ports:
     - "27017:27017"

rabbit:
   image: rabbitmq
   ports:
     - "5672:5672"

# Microservices
insertnode:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"

notelist:
   build: ./services/notelist
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"

deletenote:
   build: ./services/deltenote
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"

stat:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"

# web
stat:
   build: ./notesapp
   environment:
     SERVICE_80_NAME: "notesapp"
     SERVICE_80_TAGS: "web, notesapp"
   ports:
     - "8080:8080"
