
# Load-balancer
lb:
  image: eeacms/haproxy
  ports:
    - "80"
    - "70"
  links:
    - web
    - insertnote
  restart: always

# Infrastructure
mongodb:
   image: mongo
   ports:
     - "27017:27017"

rabbit:
   image: rabbitmq
   ports:
     - "5672:5672"

# Microservices
insertnote:
   build: ./services/insertnote
   links:
     - mongodb
     - rabbit
   ports:
     - "8080:8080"
# web
web:
   build: ./notesapp
   environment:
     SERVICE_80_NAME: "notesapp"
     SERVICE_80_TAGS: "web, notesapp"
   ports:
     - "80:3000"
